# Generated by Django 3.2.4 on 2021-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('taste', models.CharField(max_length=30)),
                ('health', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
            ],
        ),
    ]
