# Generated by Django 3.2.4 on 2021-06-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='health',
            new_name='benefits',
        ),
    ]
