# Generated by Django 3.2.4 on 2021-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_health_fruit_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='image_url',
            field=models.CharField(default='https://github.com/SannatKumar/django_images/blob/master/django_images/mango.jpg', max_length=100),
        ),
    ]
